server {
    listen 80;
    server_name localhost.test localhost 127.0.0.1;
    index index.php index.html;
    root /var/www/html/public; # O Laravel sempre aponta para a pasta public

     # Desabilitar cache
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # "app" aqui é o nome do serviço que definimos no docker-compose.yml
        fastcgi_pass app:9000; 
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}